.github/workflows/ci.yaml, .golangci.yaml, Makefile, config/deploy/local/kustomization.yaml, config/deploy/local/manager_config_patch.yaml, hack/kind-cluster.yaml, make/kind.mk, make/verify.mk
* Adds kind dependency and make targets
* Add config/deploy/local to patch the manager imagePullPolicy to "IfNotPresent" to allow it to work with locally loaded images in kind clusters.
* Add CI workflow
* Add verify make targets
* Add lint make target and golangci config
=> Add local-setup and CI GH Workflow

api/v1alpha1/provider_types.go, internal/provider/aws/aws.go, internal/provider/google/google.go, internal/provider/provider.go
Add ProviderSpecificGeoCode and ProviderSpecificWeight to api, they are both required by the DNSPolicy.
=> Provider API Update

Makefile, bundle/manifests/kuadrant-dns-operator.clusterserviceversion.yaml, config/manager/kustomization.yaml
Set default image to quay.io/kuadrant/kuadrant-dns-operator:latest
=> Set default image

docs/managedzone.md
@trepel adding this to the managed zone docs
=> state private zones as unsupported

internal/controller/managedzone_controller.go
Fixes #111 
**Validation**
- create a managed zone with a provider secret ref that doesn't exist
- check status of zone
- create secret wait for reconcile to happen (depends on how long it has been failing as will back off)
- check status of zone
=> fix for status setting and ensuring we requeue on errors

docs/provider.md
Noticed a URL formatting issue when looking at:
https://github.com/Kuadrant/docs.kuadrant.io/pull/112
=> [docs\ Update provider.md

ADOPTERS.md
**What**
Adding adopters file as we've done with [Authorino](https://github.com/Kuadrant/authorino/blob/main/ADOPTERS.md) and [Limitador](https://github.com/Kuadrant/limitador/blob/main/ADOPTERS.md)
=> Adding adopters file

internal/external-dns/provider/inmemory/inmemory.go
The `zones` map in `InMemoryClient` is not thread-safe. While using the `InMemory` provider, there is a possibility of a panic occuring when this map is read and written to concurrently. 
For example, as the Kuadrant Operator runs the DNS tests concurrently, the following error can occur occasionally:
```
fatal error: concurrent map read and map write
/workspace/internal/external-dns/provider/inmemory/inmemory.go:276
/workspace/internal/external-dns/registry/txt.go:123 +0xa2
/workspace/internal/controller/dnsrecord_controller.go:326 +0x286
/workspace/internal/controller/dnsrecord_controller.go:170 +0x9f1
main.main()
/workspace/cmd/main.go:169 +0xdc4
/go/pkg/mod/go.opencensus.io@v0.24.0/stats/view/worker.go:292 +0x9f
/usr/local/go/src/os/signal/signal_unix.go:23 +0x13
created by …
```
=> feat: RWMutex on InMemoryClient

docs/reference/dnsrecord.md
Doc updates for https://github.com/Kuadrant/dns-operator/pull/170
=> docs: Update DNSRecord API docs (OwnerID)

.github/workflows/release-helm-chart.yaml, Makefile
This PR fixes the tagging of the helm chart and includes the building of the chart when preparing a release.
=> Fix Helm workflow

internal/controller/dnsrecord_controller_test.go, internal/provider/provider.go, internal/provider/provider_test.go
=> dont proceed if a host is an apex domain

README.md, examples/kuadrant/combined-loadbalanced-dns.yaml, examples/kuadrant/geo-loadbalanced-healthchecks-dns.yaml, examples/kuadrant/weighted-loadbalanced-healthchecks.yaml, go.mod, go.sum, internal/external-dns/provider/azure/azure.go, internal/external-dns/provider/azure/azure_test.go, internal/external-dns/registry/txt.go, internal/provider/azure/azure.go, internal/provider/azure/azure_test.go, internal/provider/provider.go, test/e2e/healthcheck_test.go, test/e2e/helpers/common.go, test/e2e/multi_record_test.go, test/e2e/provider_errors_test.go, test/e2e/single_record_test.go
Add full Azure support, and enable all e2e tests.
=> Add Azure provider

internal/external-dns/provider/azure/azure.go, internal/external-dns/provider/azure/azure_test.go, internal/provider/azure/azure.go, internal/provider/azure/azure_test.go
=> gh-223: sanitize all Azure API errors

internal/provider/azure/azure.go, internal/provider/azure/azure_test.go
=> gh-232: traffic manager profile hash generation update

docs/provider.md
=> add azure mention

internal/controller/dnshealthcheckprobe_reconciler.go, internal/controller/dnsrecord_controller.go, internal/controller/dnsrecord_controller_test.go, internal/controller/dnsrecord_healthchecks.go, internal/controller/dnsrecord_healthchecks_test.go, internal/controller/helper_test.go, internal/probes/worker.go
Do not publish unhealthy endpoints or remove them from provider
=> consult healtcheck probes when publishing enpoints 

internal/probes/worker_test.go
=> add basic unit test to see passed headers are added to the request

internal/controller/dnsrecord_healthchecks_test.go
sometimes probes are listed in reverse order
=> fix flaky integration test

.github/workflows/ci-e2e.yaml, .github/workflows/ci.yaml
Adding type to merge_group as per https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#merge_group
=> specifying type to merge_group

test/scale/README.md
Update scale test docs to include wait for monitoring deployments being available.
=> docs: update scale test docs

internal/controller/dnsrecord_controller.go
=> add namespace and name to reconcile log

Makefile, api/v1alpha1/shared_types.go, cmd/main.go, config/coredns-c1/clusterrolebinding.yaml, config/coredns-c1/k8s_prometheus_patch.yaml, config/coredns-c1/kustomization.yaml, config/coredns-c1/namespace.yaml, config/coredns-c2/clusterrolebinding.yaml, config/coredns-c2/k8s_prometheus_patch.yaml, config/coredns-c2/kustomization.yaml, config/coredns-c2/namespace.yaml, coredns/examples/dnsrecord-c1.yaml, coredns/examples/dnsrecord-c2.yaml, docs/coredns/README.md, examples/kuadrant/combined-loadbalanced-dns.yaml, go.mod, go.sum, internal/controller/dnsrecord_controller.go, internal/provider/aws/aws.go, internal/provider/azure/azure.go, internal/provider/coredns/coredns.go, internal/provider/factory.go, internal/provider/google/google.go, internal/provider/inmemory/inmemory.go, internal/provider/provider.go, make/misc.mk
=> core dns lookup logic

.github/workflows/ci.yaml, Makefile, go.mod, make/verify.mk
=> bump go to keep up with vulnerability fixes

examples/kuadrant/combined-loadbalanced-dns.yaml, examples/kuadrant/geo-loadbalanced-healthchecks-dns.yaml, examples/kuadrant/loadbalanced-healthchecks-dns.yaml, examples/kuadrant/simple-dns.yaml, examples/kuadrant/simple-healthchecks-dns.yaml, examples/kuadrant/weighted-loadbalanced-healthchecks.yaml
Updating some out of date YAML samples.
Also introduced a new env var: `KUADRANT_DNS_PROVIDER_REF` so we don't have to edit the files to change provider.
=> update example DNS Records

CONTRIBUTING.md
update contributing guide with details for contacting team
=> update contributing guide with details for contacting team

.github/workflows/ci-e2e.yaml
Executed here https://github.com/Kuadrant/dns-operator/actions/runs/14405026417/job/40399405354
=> ci: Add CoreDNS provider to e2e job

Makefile
rh-pre-commit.check-secrets: DISABLED
=> remove comments

cmd/plugin/delete_owner.go, cmd/plugin/get-zone-records.go, cmd/plugin/plugin.go, go.mod, go.sum, make/cli.mk
Outline of a plugin. 
If the binary is in PATH:
`kubectl dns version`
if the binary is not in PATH
`./din/kubectl-dns version`
=> kubectl plugin for common debug information
