Kuadrant/dns-operator

- .github/workflows/ci.yaml
- Makefile
- internal/controller/dnsheathcheckprobe_controller_test.go
- internal/controller/helper_test.go
- internal/controller/managedzone_controller_test.go
- internal/controller/suite_test.go
- internal/provider/google/google_test.go
- make/act.mk
Adds all DNS related unit and integration tests from MGC repo (There aren't many :-/)
Add configuration for running tests locally and via CI:
* Add test-unit and test-integration make targets(Tests must be tagged correctly unit vs integration)
* Use actions/setup-go@v5 (Uses node20 and avoids warnings)
* Add patch to `make bundle` to avoid changing createdAt even when nothing else has updated.
* Add act tool install and make targets to help verify GH actions locally.
* Add integration_test_suite job to CI workflow.
> Add Tests and CI config

- .github/workflows/build-images.yaml
- .gitignore
- Makefile
Adds the build images CI workflow to build th eoperator, bundle and catalog images.
> Add build-images workflow

- Makefile
- bundle/manifests/dns-operator.clusterserviceversion.yaml
- bundle/metadata/annotations.yaml
- config/manifests/bases/dns-operator.clusterserviceversion.yaml
- docs/managedzone.md
- docs/provider.md
- docs/reference/managedzone.md
- [feat: Add prepare-release and manifests-gen-base-csv make targets](https://github.com/Kuadrant/dns-operator/commit/f50226cebf377dd6ddd9dc08910231e26e10bd7a)
- [bundle: update csv fields](https://github.com/Kuadrant/dns-operator/commit/ae9f0ff7795c495361b37e6081583aa0e6062927)
- [docs: add managedzone and provider docs](https://github.com/Kuadrant/dns-operator/commit/559cc35fb94d36cbc51ec89cacc22f0a3e51eaf1)
> Update base CSV, add release prep script and docs

- bundle/manifests/dns-operator.clusterserviceversion.yaml
- config/default/kustomization.yaml
- config/default/manager_metrics_patch.yaml
- config/manager/kustomization.yaml
- config/manager/manager.yaml
- config/manager/metrics_service.yaml
- config/prometheus/monitor.yaml
- config/rbac/kustomization.yaml
Removes the metrics auth proxy container from the default deployment to make it consistent with all other kuadrant components.
**Verifiction**
Terminal 1:
```
make local-setup local-deploy
kubectl -n dns-operator-system port-forward service/dns-operator-controller-manager-metrics-service 28080:8080
```
Terminal 2:
```
curl http://127.0.0.1:28080/metrics                               
certwatcher_read_certificate_errors_total 0                                                                            
certwatcher_read_certificate_total 0 …
```
> Remove metrics auth proxy

- Makefile
- config/deploy/olm/catalogsource.yaml
- config/deploy/olm/kustomization.yaml
- config/deploy/olm/namespace.yaml
- config/deploy/olm/operatorgroup.yaml
- config/deploy/olm/subscription.yaml
- docs/RELEASE.md
* Add release doc
* Update the `make prepare-release` command to properly set BUNDLE and CATALOG images
* Add olm installation and make targets `make local-setup install-olm deploy-catalog`
> release: Document release process

- .github/workflows/ci-e2e.yaml
- .github/workflows/ci.yaml
Add merge_group trigger to ci and ci-e2e. These must pass before PRs can merge.
https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue#triggering-merge-group-checks-with-github-actions
> ci: Enable CI jobs for GH merge queue

- api/v1alpha1/conditions.go
- api/v1alpha1/dnsrecord_types.go
- api/v1alpha1/zz_generated.deepcopy.go
- bundle/manifests/kuadrant.io_dnsrecords.yaml
- cmd/main.go
- config/crd/bases/kuadrant.io_dnsrecords.yaml
- internal/controller/dnsrecord_controller.go
- internal/controller/dnsrecord_controller_test.go
- internal/controller/helper_test.go
- internal/controller/managedzone_controller.go
- internal/controller/suite_test.go
- test/e2e/single_cluster_record_test.go
After applying changes to the DNS provider ruqueue DNS Record for validation; mark the Record as ready only after the validation success. 
Also, reconcile records with a default timeout to ensure the validity of the content.
>  GH-36 dns record lifecycle

- internal/external-dns/plan/plan_test.go
Update all plan tests to validate the contents of all calculated plan changes(create/update/deletes) before failing. Generally when a test fails you need to see all the calculated changes, not just the first one that failed.
> Update plan unit tests for easier debugging

- internal/common/helper.go
- internal/common/helper_test.go
- internal/controller/dnsrecord_controller.go
Randomize validation reconcilation delays
> GH-35 randomize validation time

- internal/controller/dnsrecord_controller.go
Before removing the finalizer ensure that the DNS provider removed records
> GH-38 validatie record on deletion

- internal/common/helper_test.go
- internal/controller/dnsrecord_controller.go
- internal/controller/metrics.go
Emmiting write counter as a metric and setting an upper limit for the counter after witch we give up
> GH-34 emmit write counter as a metric

- docs/RFC/distributed-dns/dnsrecord-lifecycle.md
A simple .md for people way better at docs to reference when documenting DNS Record lifecycle
> GH-75 dns record lifecycle notes

- internal/common/helper.go
- internal/controller/dnsrecord_controller.go
prevent usage of `randomizeDuration()` for less than a second and address an issue when it would randomize itself into zero duration
> Randomize duration bug

- internal/controller/dnsrecord_controller.go
- internal/controller/dnsrecord_controller_test.go
- internal/external-dns/plan/labels.go
- internal/external-dns/plan/plan.go
- internal/external-dns/plan/plan_test.go
- internal/external-dns/registry/txt.go
- internal/external-dns/registry/txt_test.go
- internal/provider/aws/aws.go
- test/e2e/multi_record_test.go
- test/e2e/single_record_test.go
- test/e2e/suite_test.go
closes #49 #85 
Initial work to modify the external-dns plan to work in the proposed way for distubuted dns.
Updates the plan to treat all endpoints passed to it (current/desired) as part of a single shared set of records. The calculation logic now takes into account other endpoints added to the plan when calculating the desired changes for any other endpoint also added.
The plan calculation logic is broken into two steps:
1. Calculate what endpoints will be created/updated and deleted based on the current and desired records passed to the plan. For each endpoint that will still exist if these changes were to be applied(create/update), a map of dnsNames and their owners is calculated.
2. Create the external-dns Changes for the endpoints calculated in step one. For all endpoints calculated …
> Gh49 distributed dns plan

- internal/controller/dnsrecord_controller.go
- internal/controller/dnsrecord_controller_test.go
When we are deleting a DNSRecord we just ignore all errors relating to the ManagedZone being missing since there is nothing we can do about it, and we don't want the record staying around forever.
Check was missing for health checks
https://github.com/Kuadrant/dns-operator/pull/78
> fix: Ignore managed zone missing errors on deletion

- internal/controller/dnsrecord_controller.go
- test/e2e/single_record_test.go
closes #88 
Fixes an issue where if you specify a wildcard rootHost value e.g. *.example.com the plan would incorrectly filter out changes for valid dnsNames e.g. foo.example.com, and only create exactly matching dnsNames e.g. *.example.com.
> fix: Handle wildcard rootHost values

- internal/controller/dnsrecord_controller.go
- internal/controller/dnsrecord_controller_test.go
- internal/external-dns/plan/plan.go
- internal/external-dns/plan/plan_test.go
closes #86 
Add step in the plan to verify the targets of all CNAME records being created or updated. If the target is calculated to be a subdomain of the plans root host, it must exist in the zone or will exist after the changes are applied.
Makes use of the plans DomainFilters since this is already used to filter down to relevant records and allows us to use the same logic to check for matches in dnsName values or targets. Plan was updated to ensure that a DomainFilter is always set for the RootHost if one is specified.
> Root host target checks

- api/v1alpha1/dnsrecord_types.go
- api/v1alpha1/managedzone_types.go
- api/v1alpha1/shared_types.go
- bundle/manifests/dns-operator.clusterserviceversion.yaml
- bundle/manifests/kuadrant.io_dnsrecords.yaml
- bundle/manifests/kuadrant.io_managedzones.yaml
- config/crd/bases/kuadrant.io_dnsrecords.yaml
- config/crd/bases/kuadrant.io_managedzones.yaml
The validations to ensure required fields were marked as required were incorrect.
Any fields that are not explicitly marked with `+optional` and do not have `omitempty` are considered required.
> fix: CRD required validations

- internal/controller/dnsrecord_controller.go
- internal/external-dns/plan/plan.go
- test/e2e/multi_record_test.go
- test/e2e/single_record_test.go
fixes #96 
Fixes an issue where the DNSRecord status was incorrectly being updated on every reconciliation even when errors were occuring causing the reconciler to go into a never ending loop and never exponentially backoff as would be expected in an error case.
> fix: DNSRecord status updates on errors

- Makefile
- cmd/main.go
- internal/controller/dnsrecord_controller_test.go
- internal/controller/helper_test.go
- internal/controller/suite_test.go
- internal/external-dns/plan/plan.go
- internal/external-dns/provider/inmemory/inmemory.go
- internal/external-dns/provider/inmemory/inmemory_test.go
- internal/provider/factory.go
- internal/provider/inmemory/inmemory.go
Adds a new provider `inmemory` for testing purposes which wraps the external dns `inmemory` provider
https://github.com/kubernetes-sigs/external-dns/tree/master/provider/inmemory. Also adds the inmemory provider to the provider factory allowing it to be used via the creation of a ManagedZone.
```
apiVersion: v1
kind: Secret
metadata:
name: inmemory-credentials
type: kuadrant.io/inmemory
data: {}
---
apiVersion: kuadrant.io/v1alpha1
kind: ManagedZone
metadata:
name: example.com
spec:
domainName: example.com
description: "example.com managed domain"
dnsProviderSecretRef:
name: inmemory-credentials
```
The external-dns provider has been modified slightly to work for some of our testing scenarios.
* Add delete zone (Removes the key from the zones map)
* Exposes the client so we can change it …
> Add inmemory provider

- internal/controller/dnsrecord_controller_test.go
- internal/controller/helper_test.go
- internal/controller/managedzone_controller_test.go
- internal/controller/suite_test.go
- internal/external-dns/provider/inmemory/inmemory.go
- internal/provider/inmemory/inmemory.go
Update the inmemory provider to work more like aws and google providers when creating a managed zone. If an ID is specified in the spec it is expected that the zone should exist and return an error otherwise. Previously created managed zones should be retrieved using the ID in the status of the managed zone.
Update integration tests to use updated inmemory provider, ensure managedzone being created has no ID in the spec. Also updates the tests to load the provider via the factory instead of overriding the factory in the suite test.
Add a test that checks we get the expected provider error when trying to use a zone id that does not exist.
> Update inmemory provider

- .github/workflows/build-images.yaml
closes #127 
* Add linux/amd64 and linux/arm64 platforms to buildah builds of operator, bundle and catalog images.
* Add qemu dependency install to image build jobs.
Brings it in-line with other kuadrant image builds (kuadrant-operator, authorino-operator etc..)
Note: Warning messages appear in the logs "Failed to decode the keys ["machine"]", but it appears to be a known issue that can be ignored. https://github.com/redhat-actions/buildah-build/issues/101
> multi-arch image builds (linux/amd64 and linux/arm64)

- internal/external-dns/provider/aws/aws.go
- internal/external-dns/provider/aws/aws_test.go
- internal/provider/provider.go
- internal/provider/provider_test.go
- test/e2e/healthcheck_test.go
- test/e2e/provider_errors_test.go
fixes: #102 
**What**
[external-dns: aws provider return zone errors](https://github.com/Kuadrant/dns-operator/commit/b636bb95714d23e76ab66f53ba78e245c4a43219)
* Replace dependency on github.com/pkg/errors with errors(Note: in latest version of the aws provider this has been replaced already)
* Collect and return list of errors for zones when submitting changes.
* Remove logic that attempts to submit changes individually if the whole set of changes fails. This currently will apply some changes that are valid but leaves the ones that are failing where we would rather nothing was created/updated if anything in the batch fails.
[Update provider SanitizeError](https://github.com/Kuadrant/dns-operator/commit/97ea058ba8b5a7db0ed208adaf638797d92aca8f)
Update provider SanitizeError function to …
> Gh102 aws errors in status

- .github/workflows/ci.yaml
- make/verify.mk
[Add verify generate and go.mod make targets](https://github.com/Kuadrant/dns-operator/pull/126/commits/9877b7de4626d747ff1b085cd250ded82ef8d0c7)
Add new make targets to verify that `make generate` and `go mod tidy` have been executed against the current code and the results committed.
Add verify-generate and verify-go-mod jobs to CI github workflow.
> Add verify generate and gomod

- go.mod
- internal/provider/google/google_test.go
fixes #95 
Ensure the RoutingPolicy Item arrays (geo or weighted) for resourceRecordSetFromEndpoint checks are sorted before checking for equality.
Replace the use of reflect.DeepEqual and equality.Semantic.DeepEqual in tests with github.com/google/go-cmp/cmp (cmp.Diff).
Produces easier to read errors when tests fail:
```
--- FAIL: Test_resourceRecordSetFromEndpoint (0.00s)
--- FAIL: Test_resourceRecordSetFromEndpoint/test_A_record (0.00s)
google_test.go:1039: resourceRecordSetFromEndpoint (-want +got):
&dns.ResourceRecordSet{
... // 3 identical fields
Rrdatas:          {"0.0.0.0"},
SignatureRrdatas: nil,
-  Ttl:              60,
+  Ttl:              600,
Type:             "A",
ServerResponse:   {},
... // 2 identical fields
}
```
Flake this PR fixes would have failed like this:
```
=== …
```
> fix: flaky test (Test_resourceRecordSetFromEndpoint)

- go.mod
- internal/controller/managedzone_controller.go
- internal/controller/managedzone_controller_test.go
- internal/provider/aws/aws.go
- internal/provider/google/google.go
- internal/provider/inmemory/inmemory.go
- internal/provider/provider.go
fixes #122 
Add managed zone validation step to ensure that when we are creating a managed zone with an ID that the corresponding domainName matches what is in the provider.
Related: 
* https://github.com/Kuadrant/dns-operator/pull/134
> fix: Validate MZ id and domainName on create

- cmd/main.go
- internal/controller/dnsrecord_controller.go
- internal/controller/dnsrecord_controller_test.go
- internal/controller/helper_test.go
fixes #82 
- Add a watch on ManagedZones in the DNSRecord controller
- Add watch namespace env var to allow specifying which namespace to watch
**Verification**
- set ```WATCH_NAMESPACES=dnstest```
- start controller
- create zone in default ns (note it is not reconciled)
- create zone in dnstest (it is reconciled)
- create dnsrecord in dnstest (it is reconciled)
- add label to managedzone see dnsrecord is reconciled when MZ is updated
> add watch and ns config

- PROJECT
- config/prometheus/monitor.yaml
- grafana/controller-resources-metrics.json
- grafana/controller-runtime-metrics.json
- grafana/custom-metrics/config.yaml
The changes in this PR are the result of running `kubebuilder edit --plugins grafana.kubebuilder.io/v1-alpha`
Verified locally via the kuadrant-operator:
- follow https://docs.kuadrant.io/0.7.0/getting-started-single-cluster/ to bring up a local cluster (using `KUADRANT_REF=main`
- create the dns operator servicemonitor (had to replace the namespace and matchLabel
```shell
kustomize build config/prometheus/ | yq e '
.metadata.namespace = "kuadrant-system" |
.spec.selector.matchLabels."control-plane" = "dns-operator-controller-manager"
' - | kubectl --context $KUBECTL_CONTEXT apply -f -
```
- port forward to grafana with `kubectl --context $KUBECTL_CONTEXT -n monitoring port-forward svc/grafana 3000:3000`
- import the 2 generated grafana dashboard json files (in this pr)
looks like this: …
> Add grafana kubebuilder plugin

- internal/controller/managedzone_controller.go
- internal/provider/aws/aws.go
- internal/provider/google/google.go
- internal/provider/google/google_test.go
- internal/provider/inmemory/inmemory.go
- internal/provider/provider.go
[context should not be stored in a struct](https://go.dev/blog/context-and-structs). Removed a stored context in the google provider.
> Fix: Removed a stored context in the google provider

- Makefile
- internal/provider/google/google.go
Fixes a lint error introduced by https://github.com/Kuadrant/dns-operator/pull/164
Unsure why it wasn't caught by that PR lint job :thinking:
> fix: Lint error ineffectual assignment to ctx

- Makefile
- make/kind.mk
- test/e2e/helpers/common.go
- test/e2e/multi_instance/README.md
- test/e2e/multi_instance/multi_record_test.go
- test/e2e/multi_instance/suite_test.go
closes #180
Adds a new `local-setup-multi` make target that can create multiple local kind clusters and updates the multi instance test suite to allow execution of tests across multiple clusters as well as namespaces.
Create 2 kind test clusters each with 2 namespaced deployments:
```
make local-setup-multi DEPLOY=true DEPLOYMENT_SCOPE=namespace DEPLOYMENT_COUNT=2 CLUSTER_COUNT=2
```
Run tests on 2 clusters each with 2 namespaced deployments:
```
make test-e2e-multi TEST_DNS_MANAGED_ZONE_NAME=dev-mz-aws TEST_DNS_NAMESPACES=dns-operator DEPLOYMENT_COUNT=2 TEST_DNS_CLUSTER_CONTEXTS=kind-kuadrant-dns-local CLUSTER_COUNT=2
```
Note: All clusters must have the same namespaces, and all namesapces must have the same managed zones.
Additional test suite updates:
* Add a check to make sure that …
> tests: Multi cluster e2e test support

- Makefile
- cmd/main.go
- config/deploy/local/kustomization.yaml
Sets the default log level to "info" and use json structured logs.  Sets the log level to debug for all local deployments and ony sets the devel option (--zap-devel) when using `make run`.
> chore: Configure default logging (info/json)

- .github/workflows/delete-release-helm-chart.yaml
- .github/workflows/release-helm-chart.yaml
- Makefile
- charts/dns-operator/.helmignore
- charts/dns-operator/Chart.yaml
- charts/dns-operator/templates/manifests.yaml
- charts/dns-operator/values.yaml
- config/helm/kustomization.yaml
- make/helm.mk
This PR introduces a way to manage a DNS Operator [Helm Chart](https://helm.sh/). This is not meant to replace the way we are building and delivering our manifests (Kustomize, OLM) but to provide an alternative (complementary) way of delivering the operator.
This early implementation uses Kustomize to create the chart template, instead of creating and maintaining new ones with Helm, to later customize the Helm only settings with its `values.yaml`
**NOTES**
* This chart (and every other operator chart we package in the future: Limitador, Authorino, etc) bundles only the operator in the same fashion OLM does.
* The operator version matches the chart version
* This first release doesn't use helm templating, it provides only the manifests previously built by Kustomize.
* The sole repository …
> Helm charts

- Makefile
- make/helm.mk
This env var is placed in the Makefile in case it's used in other targets, following authorino, limitador and kuadrant convention.
This also fixes the synchronization with the helm charts repo, that currently is failing due a missing value:
```sh
Run make helm-sync-package-created \
curl -L \
-X POST \
-H "Accept: application/vnd.github+json" \
-H "Authorization: ***" \
-H "X-GitHub-Api-Version: 2022-11-28" \
https://api.github.com/repos//helm-charts/dispatches \
-d '{"event_type":"chart-created","client_payload":{"chart":"","version":"0.4.0-alpha1", "browser_download_url": "https://github.com/Kuadrant/dns-operator/releases/download/v0.4.0-alpha1/chart-dns-operator-0.4.0-alpha1.tgz"}}'
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total …
```
> REPO env used for helm targets

- Makefile
Added to Makefile in order to be available for other targets. Forgot to push in the previous PR :(
> Missing ORG env for helm charts

- config/manager/kustomization.yaml
Should have been reverted before merging https://github.com/Kuadrant/dns-operator/pull/203
> fix: default operator img tag to latest

- .github/workflows/ci.yaml
- make/helm.mk
- make/verify.mk
* Update verify-bundle to check config directory as it also modifies the contents of the manager kustomization.
* Add verify-helm-build to check the results of `make helm-build` are committed.
* Update helm-build to be consistent with `make bundle` in what image will be set in the manager kustomization.
> ci: Update olm bundle/helm chart verification

- internal/controller/dnsrecord_controller.go
- test/e2e/provider_errors_test.go
fixes: #218  
Fixes an issue where if invalid credentials are used in the provider secret when looking for a suitable zone in the provider it would continually change the status on every reconcile. This is caused by the AWS provider adding a request id to the error which wasn't being removed in this case prior to update the record status.
> bug: Sanitize provider error messages on zone lookup

- api/v1alpha1/dnsrecord_types.go
- bundle/manifests/dns-operator.clusterserviceversion.yaml
- bundle/manifests/kuadrant.io_dnsrecords.yaml
- charts/dns-operator/templates/manifests.yaml
- config/crd/bases/kuadrant.io_dnsrecords.yaml
- internal/controller/dnsrecord_controller_test.go
The dnsrecord controller does not currently handle changes to the rootHost so is now marked as immutable to prevent it from being changed and causing odd behaviour.
In the case where you want to change the host, a new record should be created and the old one removed to ensure proper cleanup of resources in the provider.
part of: https://github.com/Kuadrant/kuadrant-operator/issues/794
> chore: Immutable RootHost field on DNSRecord

- internal/controller/dnsrecord_controller_test.go
- internal/controller/helper_test.go
The integration test suite uses the inmemory provider which is shared across all test specs. This works fine if a record is created and deleted successfully very quickly as the records in the provider(memory) will be removed, but if for any reason they aren't (secret gets removed before the record has completed its deletion reconcile for instance) they can be left behind and cause odd issues with other tests that are using the same hostname.
The changes here update the integration test suite to:
* Use a generated zone/hostname unique for each single test, this is similar in approach to the current e2e tests.
* Remove all cleanup logic from the integration test suite for record and secrets(providers). Alternative would be to wait for each deletion to complete before allowing it to continue …
> tests: Use unique zone hostnames for each integration test

- test/e2e/single_record_test.go
- test/e2e/suite_test.go
Add a test to allow us to time how long it takes for a single threaded controller to bring N records to ready when they are created more-or-less simultaneously.
closes: https://github.com/Kuadrant/dns-operator/issues/222
```
64 records:
Azure: failed at an hour
GCP: 3m57s
AWS: 6m7s
37 records (the most Azure did under an hour in my testing):
Azure: 51m37s
GCP: 2m16s
AWS: 3m11s
```
> Concurrent DNS Records test

- docs/provider.md
Adds specific perms needed for Azure and AWS
> add perms and docs for azure

- Makefile
Add the option to explicitly set ginkgo flags on e2e test runs using a makefile variable (GINKGO_FLAGS).
Example: Run all tests in parallel and exclude tests that have the "provider_errors" label:
```
make test-e2e TEST_DNS_ZONE_DOMAIN_NAME=<my domain> TEST_DNS_PROVIDER_SECRET_NAME=<my creds> TEST_DNS_NAMESPACES=<my ns> GINKGO_FLAGS='-v -p -label-filter=!provider_errors'
```
Also added a variable for enabling parallel execution "GINKGO_PARALLEL", default is false:
```
make test-e2e TEST_DNS_ZONE_DOMAIN_NAME=<my domain> TEST_DNS_PROVIDER_SECRET_NAME=<my creds> TEST_DNS_NAMESPACES=<my ns> GINKGO_PARALLEL=true
```
This is the same as `GINKGO_FLAGS='-v -p'`
> tests: Add ginkgo flags makefile variable

- .github/workflows/ci-e2e.yaml
- Makefile
- test/e2e/README.md
- test/e2e/multi_record_test.go
- test/e2e/single_record_test.go
Update the e2e github action to only run the e2e test suite for Azure on pushes (merges to main) or workflow dispatch (manually).
Updates the e2e github action to allow overriding ginkgo flags with inputs when running via workflow dispatch (manually).
Add labels to all e2e test specs.
| label           | description                                                                               |
|-----------------|-------------------------------------------------------------------------------------------|
| multi_record    | Test cases covering multiple DNSRecords updating a set of records in a zone (Distributed) |
| single_record   | Test cases covering a single DNSRecord updating a set of records in a zone                | 
| simple          | Test cases for DNSRecords using the simple …
> ci: Only run happy path tests for Azure on PRs 

- .github/workflows/ci-e2e.yaml
Add step at end of an e2e run to pull the dns operator metrics and upload them as an artifact "metrics"
Example run https://github.com/Kuadrant/dns-operator/actions/runs/11016551834?pr=246
> ci: Export dns operator metrics on success

- .github/workflows/ci-e2e.yaml
Ensure the default GINKGO_FLAGS value is always "-v", currently it is an empty string when triggered by anything other than workflow_dispatch.
Only run azure tests on pushes to main or release branches, or when triggered using workflow dispatch (manual).
> ci: Fix GINKGO_FLAGS env var in e2e

- api/v1alpha1/dnsrecord_types.go
- api/v1alpha1/dnsrecord_types_test.go
- pkg/builder/endpoints.go
- pkg/builder/endpoints_test.go
- pkg/builder/suite_test.go
Moving logic that generates endpoints from the `kuadrant-operator` repo to the DNS-operator. 
Also transfer applicable test cases and extend them a bit to cover a few edge cases since it is a unit testing and it is cheap. 
There is a bump in the GO version - gatewayAPI requires it. It is debatable if we should be using Gateways in our API. An alternative would be to use addresses and labels in our "custom" struct and have a parser on the `kuadrant-operator` side. Just like there is a `Routing` struct to avoid policy usage.
> Add api to generate endpoints

- .github/workflows/build-images.yaml
Update the image build jobs to ensure the bundle references the operator image, and the catalog references the bundle image using the tag for the git ref_name(main, v0.9.0, release-0.9 etc..) rather than the commit sha.
Before:
```
docker cp $(docker create --name temp-container quay.io/kuadrant/dns-operator-bundle:v0.6.0 tail):/manifests dns-operator-v0.6.0 && docker rm temp-container
cat dns-operator-v0.6.0/dns-operator.clusterserviceversion.yaml | yq .spec.install.spec.deployments[0].spec.template.spec.containers[0].image
quay.io/kuadrant/dns-operator:a1cc37d47d1980e9b2187587afcdb1cfb2a4bac0
```
After:
```
docker cp $(docker create --name temp-container quay.io/kuadrant/dns-operator-bundle:ci_fix_image_build_job tail):/manifests dns-operator-ci_fix_image_build_job && docker rm …
```
> ci: Fix image build jobs to use ref instead of sha on tags

- api/v1alpha1/dnsrecord_types.go
- api/v1alpha1/zz_generated.deepcopy.go
- bundle/manifests/kuadrant.io_dnsrecords.yaml
- charts/dns-operator/templates/manifests.yaml
- config/crd/bases/kuadrant.io_dnsrecords.yaml
- internal/controller/dnsrecord_controller.go
- internal/controller/dnsrecord_controller_test.go
This PR uses `zoneEndpoints` retrieved from the provider while building plan and reports them in the spec 
An is reported to a DNSRecord if an endpoint that shares rootHost with DNSrecord. 
There could be 3 cases for this: 
1. Endpoint DNSName matches root host - it is reported
2. Endpoint DNSName is a subdomain of the root host (i.e. `one.example.com` and `example.com`) - it is reported 
3. Endpoint DNS name is not sharing the host (i.e. `one.example.com` and `two.example.com`) - is not reported
The format is as proposed in #204
> Add related endpoints to DNSRecord status

- internal/common/tree.go
- internal/common/tree_test.go
add tooling to convert endpoints to a tree and back
> add tooling to convert endpoints to a tree and back

- .github/workflows/build-images-for-tag-release.yaml
- .github/workflows/build-images.yaml
- Makefile
- docs/RELEASE.md
New CI workflow named `Build and Publish Images For Tag Release` that:
```
git checkout -b release-0.7-testing 262-ci-improve-build-images-job-for-release-tags
```
Run prepare release for final version `v0.0.100`. 
```sh
make prepare-release VERSION=0.0.100 CHANNELS=stable REPLACES_VERSION=0.6.0
```
Verify local changes, commit, push and tag with the typo:
```sh
git add .
git commit -m "prepare-release: v0.7.0"
git tag v0.0.100 
git push origin release-0.7-testing
git push origin v0.0.100 
```
Verify that the build [image for release tag workflow](https://github.com/Kuadrant/dns-operator/actions/workflows/build-images-for-tag-release.yaml) is triggered and completes for the new tag
* Clean up
```
git checkout 262-ci-improve-build-images-job-for-release-tags
git push --delete origin …
```
> ci: Improve build images job for release tags

- internal/provider/aws/aws.go
- internal/provider/aws/aws_test.go
- internal/provider/codes.go
- test/e2e/multi_record_test.go
- test/e2e/provider_errors_test.go
- test/e2e/single_record_test.go
- test/e2e/suite_test.go
> Handle GEO- prefix for contintents for AWS

- api/v1alpha1/dnsrecord_types.go
> add default duration of 5m

- Makefile
- cmd/main.go
- internal/controller/dnshealthcheckprobe_reconciler.go
- internal/controller/dnsrecord_controller.go
- internal/controller/dnsrecord_healthchecks.go
- internal/controller/dnsrecord_healthchecks_test.go
- internal/controller/helper_test.go
- internal/controller/suite_test.go
- test/e2e/healthcheck_test.go
Create and delete `DNSHealthProbe` CRs during reconciliation of the DNSRecords. 
This replaced logic in `internal/controller/dnsrecord_healthchecks.go` to create new healthchecks but does not remove the code that would generate old healthchecks.
> Create/Delete HealthCheckProbeCR from DNSRecord Reconciler

- Makefile
- internal/external-dns/plan/plan.go
- internal/external-dns/plan/plan_test.go
- internal/external-dns/provider/inmemory/inmemory.go
Fixes an issue where if you had multiple records with the same host and target values all contributing to the same record set, removing one of them would cause invalid records (0 target values) to be returned from the plan.
Fixes an issue in the inmemory provider where it was allowing records with 0 target values to be added, and improves checks to avoid a panic.
Add --race option to make run task, enables the race detector on locally running instances https://go.dev/doc/articles/race_detector. This will report useful information in the logs about race related issues.
> fix: Multiple same host/target records

- internal/controller/dnshealthcheckprobe_reconciler.go
- internal/controller/dnsrecord_controller.go
- internal/probes/worker.go
- internal/probes/worker_test.go
Running with ```--race``` showed we were sharing some memory across routines. I have adjusted the design not to share memory like this now
> update probe logic not to share memory

- api/v1alpha1/conditions.go
- internal/controller/dnsrecord_controller.go
- internal/controller/dnsrecord_controller_test.go
- internal/controller/dnsrecord_healthchecks.go
- internal/controller/dnsrecord_healthchecks_test.go
- test/e2e/fixtures/healthcheck_test/geo-dnsrecord-healthchecks.yaml
Reports health checks into the status of DNSRecord. 
It also modifies the  `Ready` status. The logic is: 
- If all checks pass - the record is healthy and ready 
- If we have failing and healthy probes - the record is not healthy but ready 
- If all checks fail - the record is not healthy and not ready
> Report healtchecks to status

- charts/dns-operator/Chart.yaml
In order to be able to publish our Helm Charts in ArtifactHub.io and display valuable information in their repo site, we should provide some metadata described in https://artifacthub.io/docs/topics/annotations/helm/
> Preparing info for ArtifactHub.io

- internal/controller/dnsrecord_controller.go
- internal/controller/dnsrecord_healthchecks_test.go
also add a test case for when we remove healthchecks.
> decouple healthy from ready conditions

- api/v1alpha1/dnshealthcheckprobe_types.go
- bundle/manifests/dns-operator.clusterserviceversion.yaml
- bundle/manifests/kuadrant.io_dnshealthcheckprobes.yaml
- charts/dns-operator/templates/manifests.yaml
- config/crd/bases/kuadrant.io_dnshealthcheckprobes.yaml
- internal/probes/worker.go
- internal/probes/worker_test.go
> remove writing out lastCheckedAt status

- api/v1alpha1/dnshealthcheckprobe_types.go
- bundle/manifests/dns-operator.clusterserviceversion.yaml
- bundle/manifests/kuadrant.io_dnshealthcheckprobes.yaml
- charts/dns-operator/templates/manifests.yaml
- config/crd/bases/kuadrant.io_dnshealthcheckprobes.yaml
- internal/controller/dnsrecord_healthchecks.go
- internal/controller/dnsrecord_healthchecks_test.go
> ensure we remove healthcheckprobes if healthcheck unset

- internal/controller/dnsrecord_controller.go
- internal/controller/dnsrecord_healthchecks.go
- internal/controller/dnsrecord_healthchecks_test.go
Changes: 
- Watch probes in the dnsrecords reconciler 
- Refactor the `receivedPrematurely` to consult a list of probes (and not to retrieve probes twice I'm not passing them around) 
- If we have an operator running without `probes-enabled` flag set to true we now will ignore healthcheck spec. Before we would be waiting for probes to be created (they will not be created) 
- Added test case to capture premature reconciliation case
> Bug: ensure we watch health probes in dnsrecord controller

- internal/controller/dnsrecord_healthchecks.go
- internal/controller/dnsrecord_healthchecks_test.go
- internal/probes/worker.go
This will ensure we mark probes as unhealthy only when consecutive failures exceed the threshold. Before we would mark it as unhealthy and refuse update the record until threshold exceeded. 
This leads to a situation when the premature reconciliation on the health status change will be triggered but result in to changes and will fall back to a default validation time.
> probes unhealthy only if threshold exeeded

- make/kustomize_overlays.mk
* remove namespace- prefix
* default ns = kuadrant-dns-operator
* add common label app.kubernetes.io/part-of:kuadrant
* add patch for deployment replicas, default is 1
* add prometheus monitor to deployment
Example Usage:
```
make generate-cluster-overlay USE_REMOTE_CONFIG=true CLUSTER_OVERLAY_DIR=<path on my machine>/kuadrant-operator/config/install CLUSTER_NAME=namespaced-dns-operator DEPLOYMENT_COUNT=5
```
Produced (with slight modifications) [this](https://github.com/Kuadrant/kuadrant-operator/tree/f8e2e19d2b3a0e1fc76768ba3a1091995dfe249c/config/install/namespaced-dns-operator).
> fix: Overlay generate updates

- api/v1alpha1/dnsrecord_types.go
- bundle/manifests/dns-operator.clusterserviceversion.yaml
- bundle/manifests/kuadrant.io_dnsrecords.yaml
- charts/dns-operator/templates/manifests.yaml
- config/crd/bases/kuadrant.io_dnsrecords.yaml
> display healthy cond on get

- .gitignore
- Makefile
- config/observability/k8s_prometheus_patch.yaml
- config/observability/kustomization.yaml
- config/observability/thanos/kustomization.yaml
- test/scale/README.md
- test/scale/alerts.yaml
- test/scale/config.yaml
- test/scale/kubeburner-object-templates/aws-credentials.yaml
- test/scale/kubeburner-object-templates/azure-credentials.yaml
- test/scale/kubeburner-object-templates/dns-operator/dns-operator-deployment.yaml
- test/scale/kubeburner-object-templates/dns-operator/kustomization.yaml
- test/scale/kubeburner-object-templates/dns-operator/leader-election-role-binding.yaml
- test/scale/kubeburner-object-templates/dns-operator/metrics-service.yaml
- test/scale/kubeburner-object-templates/dns-operator/role-binding.yaml
- test/scale/kubeburner-object-templates/dns-operator/service-account.yaml
- test/scale/kubeburner-object-templates/dns-operator/service-monitor.yaml
- test/scale/kubeburner-object-templates/dnsrecord-loadbalanced.yaml
- test/scale/kubeburner-object-templates/gcp-credentials.yaml
- test/scale/kubeburner-object-templates/inmemory-credentials.yaml
- test/scale/metrics.yaml
- test/scale/metrics/.gitignore
Add a distributed dns with multiple namespaced dns operator deployments scale test using kube burner.
> Add scale test

- api/v1alpha1/dnsrecord_types.go
- bundle/manifests/dns-operator.clusterserviceversion.yaml
- bundle/manifests/kuadrant.io_dnsrecords.yaml
- charts/dns-operator/templates/manifests.yaml
- config/crd/bases/kuadrant.io_dnsrecords.yaml
Adds additional print columns to the "wide" output option to show some useful pieces of information about a DNSRecord.
```
kubectl get dnsrecord -A -l kube-burner-job=scale-test-loadbalanced -o wide
NAMESPACE      NAME                                READY   HEALTHY   ROOT HOST                                           OWNER ID   ZONE DOMAIN             ZONE ID
scale-test-0   dnsrecord-loadbalanced-aws-1        True              api.scale-test-loadbalanced.mn.hcpapps.net          30atvr20   mn.hcpapps.net          /hostedzone/xyz
scale-test-0   dnsrecord-loadbalanced-azure-1      True              api.scale-test-loadbalanced.mn.azure.hcpapps.net    8t57tjiw   mn.azure.hcpapps.net    /subscriptions/xyz/resourceGroups/kk/providers/Microsoft.Network/dnszones/mn.azure.hcpapps.net
scale-test-0 …
```
> feat: Add additional print columns to the DNSRecord resource

- .github/workflows/ci.yaml
Adds a new job to the CI jobs workflow that can be used to check the status of all ci jobs in the workflow.
Intention is this will be used as part of the merge queue configuration allowing a single job to be specified, inspired by https://github.com/orgs/community/discussions/75568#discussioncomment-10351973
Add workflow_dispatch trigger to CI workflow.
> ci: Add "CI Required Checks" job

- charts/dns-operator/Chart.yaml
Part of the work needed for https://github.com/Kuadrant/helm-charts/issues/18
This PR adds a new annotation in the Helm `Chart.yaml` meant for displaying the public key used for signing its chart packages. More info in https://artifacthub.io/docs/topics/annotations/helm/
> [ArtifactHub] GPG public key annotation

- .github/workflows/release-helm-chart.yaml
- make/helm.mk
This PR fixes the CI job for signing the packages. The GnuPG v2 stores the secret keyring using the format `kbx` and [Helm](https://helm.sh/docs/topics/provenance/) works with the legacy gpg format.
> Helm fix gpg signing target and workflow

- make/kustomize_overlays.mk
This was lasted tested against a kuadrant-operator cluster, but should work on the default setup of this repo.
* Remove prometheus monitor creation from overlay
* Change common label to app.kubernetes.io/part-of:dns-operator
* Run edit fix to remove the "commonLabels" deprecation warning.
> fix: Overlay generation

- config/coredns-multi/kuadrant-coredns-1/Corefile
- config/coredns-multi/kuadrant-coredns-2/Corefile
- config/coredns/kustomization.yaml
Set the externalTrafficPolicy to Local in the coredns LoadBalancer services to preserve the client source ip.
https://kubernetes.io/docs/tasks/access-application-cluster/create-external-load-balancer/#preserving-the-client-source-ip
Add the `edns-subnet` config to the geoip plugin to use the subnet option if it's available instead of the source ip making things easier to test locally.
```
dig @172.18.0.17 api.k.example.com +subnet=127.0.200.200 +short
```
> coredns(install): traffic policy and geoip config

- Makefile
- hack/coredns-server-list.sh
- make/dnsproviders.mk
- make/kustomize_overlays.mk
- make/misc.mk
Updates the local-setup namespaced deployments to include a per dns operator namespaced scoped instance of coredns (deployed in the same operator ns).
The coredns configuration requires all clusters and coredns instances to be running to retrieve the required dns server list, in order to achieve this during local-setup the dns provider setup is also moved to a separate task that can be executed after the cluster creation.
Update metallb task to allow subnet to be specified, required when creating more than one cluster (CLUSTER_COUNT > 1)
```
make local-setup DEPLOY=true DEPLOYMENT_SCOPE=namespace DEPLOYMENT_COUNT=2 CLUSTER_COUNT=2
```
```
$ kubectl get deployments -l app.kubernetes.io/name=coredns -A --context kind-kuadrant-dns-local-2
NAMESPACE                 NAME                 READY …
```
> coreds(deployment): Update namespaced deployments to include coredns

- internal/provider/coredns/coredns.go
- test/e2e/helpers/common.go
- test/e2e/multi_record_test.go
- test/e2e/single_record_test.go
[fix coredns(provider): break on dns query error](https://github.com/Kuadrant/dns-operator/commit/982fe59b2fdf7b0185394f1802d2753d51d224ce)
Adding back the return statement to break out of the loop and return an
error if any of the configured coredns nameservers can't be accessed.
Note: This doesn't break the tests since an NXDOMAIN response doesn't
result in an error.
[tests: Move logic for getting resolvers to the helper](https://github.com/Kuadrant/dns-operator/commit/731c3fa972113bbe74f5f1443d9744ccfca5733f)
Moves more of the logic for getting resolvers for queries into the
common helper and removes some duplication.
> Coredns provider and test updates

- test/e2e/README.md
- test/e2e/multi_record_test.go
- test/e2e/suite_test.go
Updates the multi record tests to allow multiple DNSRecords to be created in each test namespace. Uses the already existing "TEST_DNS_CONCURRENT_RECORDS" environment variable to control this, default is 1.
Note: CoreDNS does not currently support this and will error out if "TEST_DNS_CONCURRENT_RECORDS" is set to anything but 1.
Example (TEST_DNS_CONCURRENT_RECORDS=2):
```
make local-setup DEPLOY=true
make test-e2e-multi TEST_DNS_ZONE_DOMAIN_NAME=mn.hcpapps.net TEST_DNS_PROVIDER_SECRET_NAME=dns-provider-credentials-aws TEST_DNS_NAMESPACES=dnstest **TEST_DNS_CONCURRENT_RECORDS=2**
/home/mnairn/go/src/github.com/kuadrant/dns-operator/bin/ginkgo -v -tags=e2e --label-filter=multi_record ./test/e2e …
```
> tests(e2e): Allow multiple records to be created in each namespace

- .github/workflows/ci-e2e.yaml
Updates the e2e action to allow the setting of "TEST_DNS_CONCURRENT_RECORDS" and passes it into the test suite. Sets the default value to two, this will allow all the multi record tests to execute with a minimum number of two records which is more realistic and will catch more potential issues.
Related: https://github.com/Kuadrant/dns-operator/pull/440
Note: Further work is needed here to make the e2e GitHub action work with multiple clusters/namespaces. However, this will allow improved multi record testing in the meantime.
Merge after https://github.com/Kuadrant/dns-operator/pull/441
Test Run here: https://github.com/Kuadrant/dns-operator/actions/runs/14406165804
> ci(e2e): Increase default number of records created for multi record tests to two

- Makefile
- config/bind9/README.md
- config/bind9/ddns.key
- config/bind9/deployment.yaml
- config/bind9/kustomization.yaml
- config/bind9/namespace.yaml
- config/bind9/nsupdate
- config/bind9/service.yaml
- config/bind9/zone.yaml
- make/misc.mk
closes #422 
* Add [install|delete]-bind9 make targets
* Add bind9 edge server install to local-setup
* Add docs
See contents of [Readme](https://github.com/mikenairn/dns-operator/blob/b61930eb418b125822c0559c92fb95fb1655b2b4/config/bind9/README.md) for more details and verification instructions.
> feat: Add bind9 edge server to local-setup

- coredns/examples/Corefile
- coredns/plugin/README.md
- coredns/plugin/cmd/plugin/plugin.go
- coredns/plugin/go.mod
- coredns/plugin/go.sum
- coredns/plugin/kuadrant.go
Implements the transfer.Transfer interface required for zone transfers using the "transfer" plugin.
Enables the "transfer" plugin in the kuadrant build of CoreDNS along with complementary plugins "acl" and "secondary".
https://coredns.io/plugins/transfer/
**Corefile:**
```
k.example.com {
debug
errors
log
geoip geoip/GeoLite2-City-demo.mmdb {
edns-subnet
}
metadata
transfer {
to *
}
kuadrant {
kubeconfig /home/mnairn/.kube/config
}
}
```
**Verify:**
```
$ make coredns-run 
$ dig @127.0.0.1 -p 1053 -t AXFR k.example.com
; <<>> DiG 9.18.28 <<>> @127.0.0.1 -p 1053 -t AXFR k.example.com
; (1 server found)
;; global options: +cmd
k.example.com.          60      IN      SOA     ns1.k.example.com. hostmaster.k.example.com. 12345 7200 1800 86400 60
k.example.com.          60      IN      NS …
```
> coredns(plugin): Implement Transfer interface

- Makefile
- config/coredns/Corefile
- config/local-setup/coredns/deployment_config_patch.yaml
- config/local-setup/coredns/kustomization.yaml
- make/coredns.mk
Build and load the coredns docker image into the kind cluster during local-setup in order to ensure that the current version of the kuadrant coredns plugin is being used.
Adds transfer directive to default deployment Corefile
```
$ kubectl get service -A -l app.kubernetes.io/name=coredns,app.kubernetes.io/component!=metrics -o json | jq -r '[.items[] | (.status.loadBalancer.ingress[].ip)][0]'
172.18.0.17
$ dig @172.18.0.17 -t AXFR k.example.com.
; <<>> DiG 9.18.28 <<>> @172.18.0.17 -t AXFR k.example.com.
; (1 server found)
;; global options: +cmd
k.example.com.          60      IN      SOA     ns1.k.example.com. hostmaster.k.example.com. 12345 7200 1800 86400 60
k.example.com.          60      IN      NS      ns1.k.example.com.
k.example.com.          60      IN      SOA …
```
> chore: Build and load coredns image in local setup

- config/coredns/Corefile
- coredns/examples/Corefile
- coredns/plugin/README.md
- docs/coredns/README.md
closes #439 
Removes the forward directive from all Corefile examples to avoid confusion. We will only ever be using the CoreDNS instances as authoritative name servers which would not expect this option to be used.
> chore: remove forward directive from coredns examples

- .github/workflows/ci-e2e.yaml
* Removing the `pull_request_target` trigger for the CI-E2E job.
* Renamed CI-E2E -> CI-E2E-0 to allow disabling the original in GH more easily.
> ci: Rename CI-E2E job and update triggers

- .golangci.yaml
- internal/provider/coredns/coredns.go
Adds the `loggercheck` linter to detect issues with log statements, in particular to catch issues like "odd number of arguments passed as key-value pairs" which currently cause a panic when hit.
https://golangci-lint.run/usage/linters/#loggercheck
> lint: Add loggercheck linter

- api/v1alpha1/dnsrecord_types.go
- internal/controller/dnsrecord_controller.go
The spec providerRef can be nil and the watch on secrets was incorrectly still using the spec value instead of the one set in the status.
Would cause a panic if you had a secret labelled as default and a record with no provider ref.
> fix: panic when using default secret

- make/kind.mk
The make kind-load-image target was failing when using podman as the CONTAINER_TOOL. The existing implementation used kind load docker-image, which only works with Docker-created images and doesn't support images created by podman.
This change updates the kind-load-image make target to use kind load image-archive instead of kind load docker-image. The new approach:
1. Creates a temporary directory for the image archive
2. Saves the container image to a tar file using the configured CONTAINER_TOOL (works with both docker and podman)
3. Loads the image archive into the kind cluster using KIND_EXPERIMENTAL_PROVIDER
4. Properly handles cleanup of temporary files and exit codes
✅ Universal compatibility: Works with both Docker and Podman
✅ Maintains existing functionality: No breaking changes …
> Fix kind-load-image target for podman compatibility

- api/v1alpha1/conditions.go
- api/v1alpha1/dnsrecord_types.go
- internal/controller/dnsrecord_controller.go
Fixes: #487
This PR updates the DNSRecord finalizer removal logic to check for the ProviderEndpointsRemoved status condition reason before removing the finalizer. This change supports multi-cluster reconciliation of DNS records by ensuring that finalizers are only removed when DNS endpoints have been successfully removed from the provider.
Added new condition reasons:
- ConditionReasonProviderEndpointsRemoved: Indicates DNS records have been successfully removed from the provider
- ConditionReasonProviderEndpointsDeletion: Indicates DNS records are currently being deleted from the provider
Added status helper methods:
- DNSRecordStatus.ProviderEndpointsRemoved(): Returns true if the ready condition has reason "ProviderEndpointsRemoved"
- DNSRecordStatus.ProviderEndpointsDeletion(): …
> Update finalizer removal logic to check status condition for "ProviderEndpointsRemoved"

- internal/controller/dnsrecord_controller.go
- internal/controller/dnsrecord_controller_test.go
Improve watch to queue records with no provider ref on update event to the default provider secret.
Also, updating a test to set provider ref to `nil` instead of an empty string to test for #500 bug
> watch default secrets

- internal/common/labels.go
- internal/common/labels_test.go
- internal/controller/dnsrecord_controller.go
- internal/controller/dnsrecord_controller_test.go
- internal/provider/aws/aws.go
- internal/provider/azure/azure.go
- internal/provider/coredns/coredns.go
- internal/provider/endpoint/endpoint.go
- internal/provider/google/google.go
- internal/provider/inmemory/inmemory.go
- internal/provider/provider.go
- test/e2e/multi_record_test.go
- test/e2e/single_record_test.go
This PR updates the provider interface with a `.Labels()` that returns a map of expected labels for the provider. Currently the providers are only returning a default name label. It is expect these labels will be extended later.
Closes: #506
> Add provider label to DNSrecord

- .github/workflows/release.cli.yml
Add a workflow to build cli binaries
You can see a workflow run [here](https://github.com/maksymvavilov/dns-operator/actions/runs/17097389204) on [this](https://github.com/maksymvavilov/dns-operator/releases/tag/sample-release) test release of a fork 
Latest commit on the main of my fork (where the release run) is the same as on this PR.
> cli: add release workflow

- Makefile
- cmd/main.go
- internal/controller/dnsrecord_controller_test.go
- internal/controller/dnsrecord_healthchecks_test.go
- internal/controller/kubeconfig_provider_test.go
- internal/controller/suite_test.go
- test/e2e/helpers/common.go
- test/e2e/helpers/fixtures.go
Updates the integration test suite to make it possible to test both primary and secondary functionality in isolation or together in more comprehensive test cases.
The test suite creates two controller-runtime test environments (k8s api server, etcd etc..) on initialisation, one to act as a primary and one as a secondary. Each test environment runs the appropriate components for the given delegation role(based on the main application):
**Primary:**
- create multicluster-controller-runtime manager
- setup kubeconfig provider
- setup DNSRecordReconciler (DelegationRole: primary)
- setup RemoteDNSRecordReconciler
**Secondary:**
- create controller-runtime manager
- setup DNSRecordReconciler  (DelegationRole: secondary)
The test suite contains a global reference to the primary and secondary …
> Update integration test suite for primary and secondary testing 

- go.mod
- internal/controller/kubeconfig_provider_test.go
- internal/controller/remote_dnsrecord_controller.go
- internal/controller/suite_test.go
Fixes an issue with inconsistent logging between a DNSRecord reconciliation triggered by a local or remote event.
The RemoteDNSRecordReconciler creates a request specific DNSRecordReconciler instance, and is not setup via the manager meaning the log constructor that would normally be used is not called. The changes here build up the same logger and set it in the context for consistency in log statements.
> fix remote dnsrecord controller logging

- Makefile
- api/v1alpha1/conditions.go
- api/v1alpha1/dnsrecord_types.go
- cmd/main.go
- config/local-setup/dns-operator/secondary/kustomization.yaml
- internal/common/helper.go
- internal/common/helper_test.go
- internal/controller/dnsrecord_controller.go
- internal/controller/dnsrecord_controller_delegation_test.go
- internal/controller/dnsrecord_controller_test.go
- internal/controller/dnsrecord_delegation_helper.go
- internal/controller/remote_dnsrecord_controller.go
- internal/controller/suite_test.go
- internal/provider/factory.go
- make/dnsproviders.mk
closes #518
Updates the dns record reconciler to accommodate the required flow when using delegation in a multicluster (primary/secondary) configuration.
Related changes:
- #519
- #517 
- #489 
**Verification**
**Terminal 1 (primary)**
```
make multicluster-local-setup DEPLOY=false
kubectl config use-context kind-kuadrant-dns-local-1
make run
```
**Terminal 2 (secondary)**
```
export KUBECONFIG=tmp/kubeconfigs/kuadrant-local-all.kubeconfig
kubectl config use-context kind-kuadrant-dns-local-2
make run-secondary
```
**Terminal 3**
Verify cluster secrets
```
kubectl get secrets -A -l kuadrant.io/multicluster-kubeconfig=true --show-labels --context kind-kuadrant-dns-local-1
```
Expected output:
```
NAMESPACE             NAME                        TYPE     DATA   AGE     LABELS …
```
> feat: multicluster dnsrecord delegation

- api/v1alpha1/dnsrecord_types.go
- internal/controller/dnsrecord_controller_delegation_test.go
- internal/controller/dnsrecord_delegation_helper.go
- internal/provider/factory.go
Updates the naming of the authoritative dnsrecord created by the delegation feature to base the name on a hash of the root host rather than generating a random name. Naming the auth records in this way allows them to be deterministic, and in environments with more than one primary allows the names to match across clusters conforming to the sameness principals of k8s multi cluster that we want to achieve.
Updates the labels added to "authoritative" records during creation: 
```
kuadrant.io/authoritative-record=true
kuadrant.io/authoritative-record-hash=<hash of record.spec.rootHost>
```
Allows authoritative records to be more easily listed via the cli:
```
kubectl get dnsrecord -A -l kuadrant.io/authoritative-record=true
```
follow up to https://github.com/Kuadrant/dns-operator/pull/520
> update delegation authoritative record naming

- coredns/plugin/Dockerfile
- coredns/plugin/Makefile
- coredns/plugin/cmd/coredns.go
Adding git sha and version to the image and binaries being built. 
Logging them on execution. 
manually poking the binary:
`make run`:
`make docker-run`:
> add version and sha to build

- Makefile
- api/v1alpha1/dnsrecord_types.go
- api/v1alpha1/zz_generated.deepcopy.go
- bundle/manifests/dns-operator.clusterserviceversion.yaml
- bundle/manifests/kuadrant.io_dnsrecords.yaml
- charts/dns-operator/templates/manifests.yaml
- cmd/main.go
- config/crd/bases/kuadrant.io_dnsrecords.yaml
- config/rbac/role.yaml
- go.mod
- internal/controller/dnsrecord_accessor.go
- internal/controller/dnsrecord_controller.go
- internal/controller/dnsrecord_controller_delegation_test.go
- internal/controller/kubeconfig_provider_test.go
- internal/controller/remote_dnsrecord_controller.go
- internal/controller/suite_test.go
closes #562 
Adds a new field to the status of the DNSRecord resource `remoteRecordStatuses` which is intended to hold primary cluster specific statuses, one for each primary, that is reconciling it as a "remote" and adding it's endpoints to a local authoritative record. A cluster UID value is generated from the kube-system namespace for a repeatable cluster specific ID, and used as the key in the `remoteRecordStatuses` map, with each entry being a `DNSRecordStatus` for that cluster.
Note: It was mentioned we would use a "Zone ID" or something here instead of a "Cluster ID" but that wasn't really possible since this id needed to be different for every cluster, and is really a status for a cluster rather than a record on it. 
The RemoteDNSRecordReconciler is updated to reconcile the remote …
> feat: Add support for multiple primary controllers

- api/v1alpha1/dnsrecord_types.go
- bundle/manifests/dns-operator.clusterserviceversion.yaml
- bundle/manifests/kuadrant.io_dnsrecords.yaml
- charts/dns-operator/templates/manifests.yaml
- config/crd/bases/kuadrant.io_dnsrecords.yaml
- internal/controller/dnsrecord_controller_test.go
- internal/controller/helper_test.go
- internal/controller/suite_test.go
The issue we have now is that `false` for a boolean is treated like a `default` value and is omitted. Se [here](https://github.com/golang/go/issues/13284#issuecomment-157288692).  
The typical resolution is to make a primitive into a pointer that gives you 3 values to work with. In our case, it is not optimal as the default value and the absence of a value are functionally the same. Right now, to solve this, we are forbidding setting `delegate` if it was unset and unsetting if it was set. 
I'm changing the CEL validation rules to only forbid an update from `nil` to `true` and from `true` to `nil`. The rest of the cases are covered by the immutability rule. 
Here is a breakdown.
Rule: `oldSelf == self` 
| old   | new   | got   | want  |
|-------|-------|-------|-------|
| false | nil   | …
> equate not set delegate field to false in CR validation

- docs/dns_record_delegation.md
- docs/reference/dnsrecord.md
Document the meaning of the delegation flag in a dns record.
> docs: dns record delegation
